# ============================================================
# Deployment — Frontend Nginx
# Sirve el HTML estático y enruta al backend
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend

  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      # Nginx necesita correr como root para el puerto 80
      # lo mitigamos con securityContext a nivel de contenedor
      securityContext:
        runAsNonRoot: false

      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP

          # Le decimos al frontend dónde está el backend
          # En Kubernetes la URL interna es el nombre del Service
          env:
            - name: API_URL
              value: "http://{{ include "devops-app.fullname" . }}-backend:{{ .Values.config.backendPort }}"

          resources:
            requests:
              cpu:    {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu:    {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}

          # Liveness — comprueba que Nginx responde
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

          # Readiness — espera a que Nginx esté listo antes de recibir tráfico
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
