# ============================================================
# Service — Frontend
# Tipo ClusterIP: el Ingress enruta hacia aquí
# El usuario nunca accede directamente a este Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}   # ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}        # 80
      targetPort: {{ .Values.frontend.service.port }}  # 80 del contenedor Nginx
      protocol: TCP
      name: http
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
