# ============================================================
# Service — Backend
# Tipo ClusterIP: solo accesible dentro del clúster
# El frontend lo llama por nombre, nunca por IP
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}   # ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}        # puerto del Service
      targetPort: {{ .Values.backend.service.port }}  # puerto del contenedor
      protocol: TCP
      name: http
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend   # busca Pods con este label
